name: Build and release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sdcc

    steps:
    - uses: actions/checkout@v3
    - name: Install Boost
      run: sudo apt-get -y update && sudo apt-get -y install libboost-all-dev
    - name: configure
      run: CXXFLAGS=-std=c++98 ./configure --disable-device-lib --disable-werror --disable-z80-port --disable-z180-port --disable-r2k-port --disable-r3ka-port --disable-gbz80-port --disable-tlcs90-port --disable-ds390-port --disable-ds400-port --disable-pic14-port --disable-pic16-port --disable-hc08-port --disable-s08-port --disable-stm8-port
    - name: make
      run: make
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: sdcc/bin/sdcc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
